var commonPhrases = [
  "Actions speak louder than words",
  "The early bird catches the worm",
  "A penny for your thoughts",
  "Bite the bullet",
  "Hit the nail on the head",
  "Let the cat out of the bag",
  "Don't cry over spilt milk",
  "Two wrongs don't make a right",
  "The grass is always greener on the other side",
  "Every cloud has a silver lining",
  "A stitch in time saves nine",
  "Beggars can't be choosers",
  "Beauty is in the eye of the beholder",
  "Better late than never",
  "Curiosity killed the cat",
  "Easy come, easy go",
  "Fortune favors the bold",
  "Ignorance is bliss",
  "Kill two birds with one stone",
  "No pain, no gain",
  "Out of sight, out of mind",
  "Practice makes perfect",
  "Rome wasn't built in a day",
  "The squeaky wheel gets the grease",
  "When in Rome, do as the Romans do",
  "You can't make an omelette without breaking eggs",
  "A bird in the hand is worth two in the bush",
  "A chain is only as strong as its weakest link",
  "A penny saved is a penny earned",
  "All roads lead to Rome",
  "Beauty is only skin deep",
  "Don't count your chickens before they hatch",
  "Empty vessels make the most noise",
  "Good things come to those who wait",
  "If you can't stand the heat, get out of the kitchen",
  "It's better to be safe than sorry",
  "Look before you leap",
  "Money can't buy happiness",
  "Nothing ventured, nothing gained",
  "People who live in glass houses shouldn't throw stones",
  "The best things in life are free",
  "The devil is in the details",
  "The grass is always greener on the other side",
  "There's no smoke without fire",
  "Time heals all wounds",
  "Too many cooks spoil the broth",
  "What goes around comes around",
  "You reap what you sow",
  "A picture is worth a thousand words",
  "Actions speak louder than words",
  "All is fair in love and war",
  "An apple a day keeps the doctor away",
  "Barking up the wrong tree",
  "Better safe than sorry",
  "Birds of a feather flock together",
  "Blood is thicker than water",
  "Charity begins at home",
  "Cleanliness is next to godliness",
  "Cry over spilled milk",
  "Don't put all of your eggs in one basket",
  "Fight fire with fire",
  "Fool me once, shame on you. Fool me twice, shame on me",
  "He who laughs last, laughs best",
  "Honesty is the best policy",
  "If it ain't broke, don't fix it",
  "If the shoe fits, wear it",
  "If you can't beat them, join them",
  "In for a penny, in for a pound",
  "It takes two to tango",
  "Keep your friends close and your enemies closer",
  "Like father, like son",
  "Make hay while the sun shines",
  "No use crying over spilled milk",
  "One man's trash is another man's treasure",
  "Practice what you preach",
  "Put all your eggs in one basket",
  "Rome wasn't built in a day",
  "Sticks and stones may break my bones, but words will never hurt me",
  "The early bird catches the worm",
  "The enemy of my enemy is my friend",
  "The grass is always greener on the other side",
  "The pot calling the kettle black",
  "There's no place like home",
  "Time flies when you're having fun",
  "To each his own",
  "Two heads are better than one",
  "When the going gets tough, the tough get going",
  "You can't have your cake and eat it too",
  "You can't teach an old dog new tricks",
  "A chain is only as strong as its weakest link",
  "A friend in need is a friend indeed",
  "A watched pot never boils",
  "All is fair in love and war",
  "Don't cry over spilt milk",
  "Don't judge a book by its cover",
  "Familiarity breeds contempt",
  "Good things come to those who wait",
  "He who hesitates is lost",
  "If at first you don't succeed, try, try again",
  "Out of sight, out of mind",
  "The apple doesn't fall far from the tree",
  "The early bird catches the worm",
  "The grass is always greener on the other side",
  "The pen is mightier than the sword",
  "There's no time like the present",
  "Time is money",
  "Two wrongs don't make a right"
];