var commonPhrases = [
  "Actions speak louder than words",
  "The early bird catches the worm",
  "A penny for your thoughts",
  "Bite the bullet",
  "Hit the nail on the head",
  "Let the cat out of the bag",
  "Don't cry over spilt milk",
  "Two wrongs don't make a right",
  "The grass is always greener on the other side",
  "Every cloud has a silver lining",
  "A stitch in time saves nine",
  "Beggars can't be choosers",
  "Beauty is in the eye of the beholder",
  "Better late than never",
  "Curiosity killed the cat",
  "Easy come, easy go",
  "Fortune favors the bold",
  "Ignorance is bliss",
  "Kill two birds with one stone",
  "No pain, no gain",
  "Out of sight, out of mind",
  "Practice makes perfect",
  "Rome wasn't built in a day",
  "The squeaky wheel gets the grease",
  "When in Rome, do as the Romans do",
  "You can't make an omelette without breaking eggs",
  "A bird in the hand is worth two in the bush",
  "A chain is only as strong as its weakest link",
  "A penny saved is a penny earned",
  "All roads lead to Rome",
  "Beauty is only skin deep",
  "Don't count your chickens before they hatch",
  "Empty vessels make the most noise",
  "Good things come to those who wait",
  "If you can't stand the heat, get out of the kitchen",
  "It's better to be safe than sorry",
  "Look before you leap",
  "Money can't buy happiness",
  "Nothing ventured, nothing gained",
  "People who live in glass houses shouldn't throw stones",
  "The best things in life are free",
  "The devil is in the details",
  "The grass is always greener on the other side",
  "There's no smoke without fire",
  "Time heals all wounds",
  "Too many cooks spoil the broth",
  "What goes around comes around",
  "You reap what you sow",
  "A picture is worth a thousand words",
  "Actions speak louder than words",
  "All is fair in love and war",
  "An apple a day keeps the doctor away",
  "Barking up the wrong tree",
  "Better safe than sorry",
  "Birds of a feather flock together",
  "Blood is thicker than water",
  "Charity begins at home",
  "Cleanliness is next to godliness",
  "Cry over spilled milk",
  "Don't put all of your eggs in one basket",
  "Fight fire with fire",
  "Fool me once, shame on you. Fool me twice, shame on me",
  "He who laughs last, laughs best",
  "Honesty is the best policy",
  "If it ain't broke, don't fix it",
  "If the shoe fits, wear it",
  "If you can't beat them, join them",
  "In for a penny, in for a pound",
  "It takes two to tango",
  "Keep your friends close and your enemies closer",
  "Like father, like son",
  "Make hay while the sun shines",
  "No use crying over spilled milk",
  "One man's trash is another man's treasure",
  "Practice what you preach",
  "Put all your eggs in one basket",
  "Rome wasn't built in a day",
  "Sticks and stones may break my bones, but words will never hurt me",
  "The early bird catches the worm",
  "The enemy of my enemy is my friend",
  "The grass is always greener on the other side",
  "The pot calling the kettle black",
  "There's no place like home",
  "Time flies when you're having fun",
  "To each his own",
  "Two heads are better than one",
  "When the going gets tough, the tough get going",
  "You can't have your cake and eat it too",
  "You can't teach an old dog new tricks",
  "A chain is only as strong as its weakest link",
  "A friend in need is a friend indeed",
  "A watched pot never boils",
  "All is fair in love and war",
  "Don't cry over spilt milk",
  "Don't judge a book by its cover",
  "Familiarity breeds contempt",
  "Good things come to those who wait",
  "He who hesitates is lost",
  "If at first you don't succeed, try, try again",
  "Out of sight, out of mind",
  "The apple doesn't fall far from the tree",
  "The early bird catches the worm",
  "The grass is always greener on the other side",
  "The pen is mightier than the sword",
  "There's no time like the present",
  "Time is money",
  "For crying out loud",
  "Eat your words",
  "Money talks",
  "Out of the frying pan and into the fire",
  "Driving me up the wall",
  "Hold the fort",
  "Off the record",
  "Go against the grain",
  "Break the ice",
  "Your guess is as good as mine",
  "Water under the bridge",
  "Fish out of water",
  "Blow off steam",
  "Call it quits",
  "Come full circle",
  "In deep water",
  "Break the bank",
  "Pull a rabbit out of a hat",
  "Climbing the walls",
  "Go off the rails",
  "The ball is in your court",
  "Under the radar",
  "My hands are tied",
  "Light at the end of the tunnel",
  "Make waves",
  "Call it a day",
  "Out of the blue",
  "Out of left field",
  "Long shot",
  "Give the benefit of the doubt",
  "Don’t rock the boat",
  "Cutting corners",
  "Leave no stone unturned",
  "Spill the beans",
  "Slow and steady wins the race",
  "Rule of thumb",
  "Jump the gun",
  "Blow your own trumpet",
  "Throw caution to the wind",
  "To add fuel to the fire",
  "Face the music",
  "Fit as a fiddle",
  "Cost the earth",
  "In a nutshell",
  "Fly off the handle",
  "Pull out all the stops",
  "Get down to brass tacks",
  "Pulling your leg",
  "Hindsight is 20/20",
  "Clean slate",
  "Beat a hasty retreat",
  "Miss the boat",
  "In over your head",
  "Kick the bucket",
  "Over my dead body",
  "Knuckle down",
  "Drive a hard bargain",
  "Dressed to the nines",
  "Cross that bridge when you come to it",
  "Under your nose",
  "Play it safe",
  "In the same boat",
  "Skeleton in the closet",
  "Through thick and thin",
  "Make a long story short",
  "Live and let live",
  "The elephant in the room",
  "Shoot for the stars",
  "In the nick of time",
  "On pins and needles",
  "Neck and neck",
  "Take it with a grain of salt",
  "The writing on the wall",
  "On cloud nine",
  "Go the extra mile",
  "Down to the wire",
  "Don’t give up your day job",
  "Give it a whirl",
  "Cold feet",
  "Walk a mile in someone else’s shoes",
  "Between a rock and a hard place",
  "Cut to the chase",
  "Hand over fist",
  "Cry wolf",
  "Do unto others as you would have them do unto you",
  "Read between the lines",
  "Head in the sand",
  "Get a taste of your own medicine",
  "All in the same boat",
  "Far cry from",
  "See eye to eye",
  "Grasp at straws",
  "Make a mountain out of a molehill",
  "All bark and no bite",
  "Up the ante",
  "Penny for your thoughts",
  "A dime a dozen",
  "Two wrongs don't make a right",
  "Take it with a pinch of salt",
  "Keep your eyes peeled",
  "Burning the midnight oil",
  "Ballpark figure",
  "Find your feet",
  "Seeing is believing",
  "Your heart is in the right place",
  "Big fish in a small pond",
  "Get cold feet",
  "Pull yourself together",
  "Go with the flow",
  "Hard nut to crack",
  "Feeling blue",
  "Rock the boat",
  "Go out on a limb",
  "As easy as pie",
  "A piece of cake",
  "Cat’s out of the bag",
  "Burn the midnight oil",
  "All that glitters is not gold",
  "Know the ropes",
  "Hit the ground running",
  "Let nature take its course",
  "Let sleeping dogs lie",
  "Put the cart before the horse",
  "Cry over spilt milk",
  "It’s not rocket science",
  "Easy does it",
  "Turn a blind eye",
  "Gravy train",
  "Music to my ears",
  "Go down in flames",
  "Lend a hand",
  "Out of the woods",
  "Once bitten, twice shy",
  "Beating around the bush",
  "Speak volumes",
  "Hang in there",
  "Have your head in the clouds",
  "Clam up",
  "Eat humble pie",
  "Hit the books",
  "The sky’s the limit",
  "Keep an eye on it",
  "Not playing with a full deck",
  "Burning the candle at both ends",
  "Down to earth",
  "Work like a charm",
  "Drive someone up the wall",
  "Against the grain",
  "Miss the mark",
  "A blessing in disguise",
  "Speak your mind",
  "Keep a lid on it",
  "Second wind",
  "Run out of steam",
  "Steal someone’s thunder",
  "Read the room",
  "Can't judge a book by its cover",
  "For the birds",
  "More than you can shake a stick at",
  "Off the beaten track",
  "Don’t judge a book by its cover",
  "Cold shoulder",
  "Over the moon",
  "Raining cats and dogs",
  "The best of both worlds",
  "Back to the drawing board",
  "Don’t cry wolf",
  "It’s a small world",
  "Hit the jackpot",
  "The proof is in the pudding",
  "You can’t judge a book by its cover",
  "Apple of my eye",
  "Green with envy",
  "An arm and a leg",
  "Snug as a bug in a rug",
  "Don’t beat a dead horse",
  "Like two peas in a pod",
  "Get out of hand",
  "On the fence",
  "Money doesn’t grow on trees",
  "Skeletons in the closet",
  "Catch someone red-handed",
  "Rough around the edges",
  "Cut the mustard",
  "Quick on the draw",
  "Up in arms",
  "Hold your horses",
  "Jump on the bandwagon",
  "In hot water",
  "Go on a wild goose chase",
  "Chip on your shoulder",
  "Off the hook",
  "Whole nine yards",
  "Be in the driver’s seat",
  "Raise the bar",
  "Let bygones be bygones",
  "Beat around the bush",
  "Add insult to injury",
  "Twist someone’s arm",
  "Have a bone to pick",
  "Couch potato",
  "More than meets the eye",
  "Every dog has its day",
  "Give someone the cold shoulder",
  "Once in a blue moon",
  "At the drop of a hat",
  "Last but not least",
  "Don’t count your chickens before they hatch",
  "Throw in the towel",
  "Dead as a doornail",
  "Back to square one",
  "Out of your league",
  "As good as gold",
  "Fingers crossed",
  "Make ends meet",
  "Have your cake and eat it too",
  "Two peas in a pod",
  "Backseat driver",
  "Under the weather",
  "Set in stone",
  "Have bigger fish to fry",
  "The last straw",
  "Cost an arm and a leg",
  "Over the hill",
  "Hit the sack",
  "Neck of the woods",
  "Caught between a rock and a hard place",
  "Get your act together",
  "Close, but no cigar",
  "Chalk it up",
  "Keep your chin up",
  "Like clockwork",
  "When pigs fly",
  "Feel under the weather",
  "Walking on eggshells",
  "Go bananas",
  "Don’t bite the hand that feeds you",
  "On the ball",
  "Pass the buck",
  "By the skin of your teeth",
  "Once in a lifetime",
  "An uphill battle",
  "Laughter is the best medicine",
  "One for the books",
  "Keep your head above water",
  "At the end of the day",
  "Draw a blank",
  "Put your best foot forward",
  "Piece of cake",
  "On thin ice",
  "Have a change of heart",
  "Get something off your chest",
  "Bring home the bacon",
  "Method to the madness",
  "Take it easy",
  "Change of heart",
  "Play it by ear",
  "Full of beans",
  "Shape up or ship out",
  "Don’t put all your eggs in one basket",
  "Mountain out of a molehill",
  "Against all odds"
];